[Chore] PR CI Workflow (#5)
* workflow to check PR title

* Fix error message

* CI build healthcheck

* Run container detached mode

* Use IP instead of localhost

* Build and test in same step

* fix endpoint to check

* Add sleep

* Minor fix to output

* fix - add sleep

* Fix echo

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -5,13 +5,51 @@ on:
     branches:
       - main
 
-
 jobs:
   check-pr-title:
+    name: Check PR Title
     runs-on: ubuntu-latest
     steps:
     - name : Title of PR
       env:
         TITLE: ${{ github.event.pull_request.title }}
       run: |
-        echo "The Title of your PR is ${TITLE}"
+        if [[ "${TITLE}" =~ ^\[(Chore|Docs|Minor|Major)\] ]]; then
+            echo "The title of the PR is compliant"
+        else
+            echo "Non-compliant PR title! Please fix and push another commit"
+            exit 1
+        fi
+
+  ci:
+    name: Continuous Integration
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Build image
+      run: docker build -t astro .
+
+    - name: Run app container
+      run: |
+        docker run -d --rm -p 80:80 --name app astro
+
+    - name: Check app status
+      run: |
+        ENDPOINT="http://127.0.0.1/health-check"
+
+        echo "Wait 5 seconds for server to be ready"
+        sleep 5
+
+        curl -s $ENDPOINT
+
+        STATUS=$(curl -s $ENDPOINT | jq -r '.statusText')
+
+        if [[ "$STATUS" == "OK" ]]; then
+          echo -e "\nStatus is OK"
+        else
+          echo -e "\nERROR: Status is not OK"
+          docker logs app
+          exit 1
+        fi
