ci: release

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -28,32 +28,28 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
-    - name: Debug
+    - name: Build image
+      run: docker build -t astro .
+
+    - name: Run app container
       run: |
-        echo "${{ github.actor }}"
+        docker run -d --rm -p 80:80 --name app astro
 
-    # - name: Build image
-    #   run: docker build -t astro .
+    - name: Check app status
+      run: |
+        ENDPOINT="http://127.0.0.1/health-check"
 
-    # - name: Run app container
-    #   run: |
-    #     docker run -d --rm -p 80:80 --name app astro
+        echo "Wait 5 seconds for server to be ready"
+        sleep 5
 
-    # - name: Check app status
-    #   run: |
-    #     ENDPOINT="http://127.0.0.1/health-check"
+        curl -s $ENDPOINT
 
-    #     echo "Wait 5 seconds for server to be ready"
-    #     sleep 5
+        STATUS=$(curl -s $ENDPOINT | jq -r '.statusText')
 
-    #     curl -s $ENDPOINT
-
-    #     STATUS=$(curl -s $ENDPOINT | jq -r '.statusText')
-
-    #     if [[ "$STATUS" == "OK" ]]; then
-    #       echo -e "\nStatus is OK"
-    #     else
-    #       echo -e "\nERROR: Status is not OK"
-    #       docker logs app
-    #       exit 1
-    #     fi
+        if [[ "$STATUS" == "OK" ]]; then
+          echo -e "\nStatus is OK"
+        else
+          echo -e "\nERROR: Status is not OK"
+          docker logs app
+          exit 1
+        fi
